gitea:
  valkey-cluster:
    enabled: false
  valkey:
    enabled: true
  postgresql:
    enabled: false
  postgresql-ha:
    enabled: false

  persistence:
    enabled: false

  gitea:
    config:
      server:
        ROOT_URL: "https://git.local.kyma.dev/"
      database:
        DB_TYPE: sqlite3
      session:
        PROVIDER: memory
      cache:
        ADAPTER: memory
      queue:
        TYPE: level
    admin:
      username: "admin"
      password: "password"
      email: "admin@example.com"

